<div class="container">

    <div class="page-header">
        <h1>Ajout d'un film</h1>
    </div>
    
    <?php if ($this->message != '') : ?>
        <div class="alert alert-success">
            <?= $this->message ?>
            <a class="btn btn-success" href="/film/show/filmId/<?= $this->filmId ?>">Voir le film</a>
        </div>
    <?php endif; ?>
    
    <?php 
        
        $this->form->setAttrib('class', 'form-horizontal');
        $this->form->setAttrib('role', 'form');
        $this->form->setDecorators(
            array(
                
                array('ViewScript',
                    
                    array(
                        'viewScript' => 'film/add.form.phtml',
                    ),
                    
                ),
                'Form'
                
            )
        );
    
        echo $this->form;
    ?>
    
</div>