<form class="form-horizontal">
    
    <?php 
        foreach($this->element as $element) : 
        if ($element->helper != "formButton") :
    ?>
        <div class="form-group">
            <?php
            $element->setDecorators(
                    array(
                        'ViewHelper',
                        array('Description', array('class'=> 'help-block')),
                        'Errors',
                        array('HtmlTag', array(
                                'tag' => 'div', 
                                'class' => 'col-sm-10'
                            )
                        ),
                        array('Label', array('class' => 'col-sm-2 control-label')),
                    )
                );
            echo $element;
            ?>
        </div>     
    <?php 
        endif; 
        endforeach; 
    ?>
    
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php 
                $this->element->add->setDecorators(array('ViewHelper'));
                echo $this->element->add;
            ?>
        </div>
    </div>
    
</form>
