<div class="container">
    <div class="page-header">
        <h1>Liste de 10 films</h1>
    </div>
    
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <td class="text-center">Titre</td>
                <td class="text-center">Date de sortie</td>
                <td class="text-center">PEGI</td>
                <td class="text-center">Durée</td>
                <td class="text-center">Prix</td>
                <td class="text-center">Actions</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->filmList as $film) : ?>
                <tr>
                    <td>
                        <a href="/film/show/filmId/<?= $film->getFilmId() ?>">
                            <?= $film->getTitle() ?>
                        </a>
                    </td>
                    <td class="text-center"><?= $film->getReleaseYear() ?></td>
                    <td class="text-center"><?= $film->getRating() ?></td>
                    <td class="text-center"><?= $film->getLength() ?> minutes</td>
                    <td class="text-center"><?= $film->getReplacementCost() ?> $</td>
                    <td class="text-center">
                        <a class="btn btn-danger btn-xs" href="/film/delete/filmId/<?= $film->getFilmId() ?>">
                            X
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>