<form class="form-horizontal">
    
    <div class="form-group">
        <?php 
            $this->element->firstName->setDecorators(
                array(
                    'ViewHelper',
                    array('Description', array('class'=> 'help-block')),
                    array('HtmlTag', array(
                            'tag' => 'div', 
                            'class' => 'col-sm-10'
                        )
                    ),
                    array('Label', array('class' => 'col-sm-2 control-label')),
                )
            );
            echo $this->element->firstName;
        ?>
    </div>    
    
    <div class="form-group">
        <?php 
            $this->element->lastName->setDecorators(
                array(
                    'ViewHelper',
                    array('Description', array('class'=> 'help-block')),
                    //'Errors',
                    array('HtmlTag', array(
                            'tag' => 'div', 
                            'class' => 'col-sm-10'
                        )
                    ),
                    array('Label', array('class' => 'col-sm-2 control-label')),  
                )
            );
            echo $this->element->lastName;
        ?>
    </div>       
    
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php 
                $this->element->add->setDecorators(array('ViewHelper'));
                echo $this->element->add;
            ?>
        </div>
    </div>
    
</form>
