<div class="container">

    <div class="page-header">
        <h1>Ajout d'un acteur</h1>
    </div>
    
    <?php if ($this->message != '') : ?>
        <div class="alert alert-success">
            <?= $this->message ?>
        </div>
    <?php endif; ?>
    
    <?php 
        
        $this->form->setAttrib('class', 'form-horizontal');
        $this->form->setAttrib('role', 'form');
        $this->form->setDecorators(
            array(
                'FormErrors',
                array('ViewScript',
                    
                    array(
                        'viewScript' => 'actor/add.form.phtml',
                    ),
                    
                ),
                'Form'
                
            )
        );
    
        echo $this->form;
    ?>

    
</div>