<div class="container">
    <div class="page-header row">
        <div class="col-md-8">
            <h1>List de 10 acteurs</h1>
        </div>
        <div class="col-md-4">
            <a class="btn btn-primary pull-right" href="/actor/add">Ajouter un acteur</a>
        </div>
    </div>
    
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <td class="text-center">Prénom</td>
                <td class="text-center">Nom</td>
                <td class="text-center">Actions</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->actorList as $actor) : ?>
            
                <tr>
                    <td>
                        <a href="/actor/show/actorId/<?= $actor->getActorId() ?>">
                            <?= $actor->getFirstName() ?>
                        </a>
                    </td>
                    <td><?= $actor->getLastName() ?></td>
                    <td class="text-center">
                        <a class="btn btn-danger btn-xs" href="/actor/delete/actorId/<?= $actor->getActorId() ?>">
                            X
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>