<div class="container">

    <div class="page-header">
        <h1>Fiche acteur</h1>
    </div>
    
    <h3>Nom: <span class="text-muted"><?= $this->actor->getLastName() ?></span></h3>
    <h3>Prénom: <span class="text-muted"><?= $this->actor->getFirstName() ?></span></h3>
    
    <p>Date de dernière modification: 
        <span class="text-muted"><?= $this->actor->getLastUpdate() ?></span>
    </p>    
        
    
    <a class="btn btn-primary" href="/actor">Retour à la liste des acteurs</a>
    
</div>